package cc.g1cloud.greenhousessid31.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import net.minidev.json.JSONObject;


@Getter
@Setter
@DynamoDBTable(tableName = "ssid31_greenhouse")
public class GreenhouseTelemetry {

 //   @DynamoDBAutoGeneratedTimestamp
    @DynamoDBHashKey
    private Long timestamp;



    @DynamoDBAttribute(attributeName = "device_data")
    private DeviceData deviceData;


}



