package cc.g1cloud.greenhousessid31.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import net.minidev.json.JSONObject;


@Getter
@Setter
@DynamoDBTable(tableName = "greenhouse_ssid31_esp")
public class GreenhouseTelemetry {

 //   @DynamoDBAutoGeneratedTimestamp
    @DynamoDBHashKey(attributeName = "device_id")
    private String deviceId;

   @DynamoDBAttribute
    private Long timestamp;

    @DynamoDBAttribute(attributeName = "device_data")
    private DeviceData deviceData;


}



