package cc.g1cloud.greenhousessid31.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

@DynamoDBTable(tableName = "ssid31_greenhouse")
public class GreenhouseTelemetry {

 //   @DynamoDBAutoGeneratedTimestamp
    @DynamoDBHashKey
    private Long timestamp;

    @DynamoDBAttribute(attributeName = "temperature")
    private Double temperature;

    @DynamoDBAttribute
    private Number humidity;

    @DynamoDBAttribute
    private long upTime;

}



