server:
  port: 8088

dynamodb:
  service-endpoint: "dynamodb.us-east-1.amazonaws.com"
  signing-region: "us-east-1"
  access-key: "AKIARPA6MQFN6EGT2G6J"
  secret-key: "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"

web:
  cors:
    enabled: true
    allowed-origins:
      - "http://localhost:3000"
      - "https://localhost:3000"

logging:
  level:
    ROOT: INFO
    cc.g1cloud.greenhousessid31.controller: DEBUG


